#!/usr/bin/env python3
"""
Generates the "Formal Grammar" documentation page from the PLY parser.

Reads the grammar productions straight from tasknet_parser.py (via
extract_grammar) and renders a prettified EBNF where terminal token names
(LBRACE, SEMI, TASKNET, ...) are replaced with their concrete spellings
("{", ";", "tasknet", ...). Also refreshes grammar.txt so the raw and pretty
forms stay in sync.

Run after changing the parser:

    python3 src/smt/gen_grammar_doc.py
"""

from __future__ import annotations
import re
from pathlib import Path

import extract_grammar

# Punctuation / operator tokens -> concrete spelling (stable; mirrors t_* rules).
PUNCT = {
    "LBRACE": "{", "RBRACE": "}",
    "LPAREN": "(", "RPAREN": ")",
    "LBRACKET": "[", "RBRACKET": "]",
    "COLON": ":", "SEMI": ";", "COMMA": ",",
    "DOT": ".", "DOTDOT": "..",
    "EQ": "=",
    "PLUS_EQ": "+=", "MINUS_EQ": "-=",
    "PLUS_RATE": "+~", "MINUS_RATE": "-~", "ASSIGN_RATE": "=~",
    "GE": ">=", "LE": "<=", "GT": ">", "LT": "<",
    "IMPLIES": "->",
}

# Lexical categories -> lowercase placeholders (rendered unquoted).
PLACEHOLDERS = {"NAME": "name", "NUMBER": "number", "STRING": "string"}


def load_keyword_tokens(parser_src: str) -> dict[str, str]:
    """Return {TOKEN: keyword_string} parsed from the parser's `reserved` dict."""
    m = re.search(r"reserved\s*=\s*\{(.*?)\}", parser_src, re.S)
    if not m:
        raise RuntimeError("Could not find `reserved` dict in parser source")
    pairs = re.findall(r'"([^"]+)"\s*:\s*"([A-Z0-9_]+)"', m.group(1))
    return {tok: kw for kw, tok in pairs}


def build_terminal_map(parser_src: str) -> dict[str, str]:
    """TOKEN -> rendered symbol (terminals quoted, placeholders bare)."""
    term: dict[str, str] = {}
    for tok, lit in PUNCT.items():
        term[tok] = f'"{lit}"'
    for tok, kw in load_keyword_tokens(parser_src).items():
        term[tok] = f'"{kw}"'
    for tok, ph in PLACEHOLDERS.items():
        term[tok] = ph
    return term


def convert_symbol(sym: str, term: dict[str, str]) -> str:
    if sym == "empty":
        return "ε"
    return term.get(sym, sym)


def convert_rhs(rhs: str, term: dict[str, str]) -> str:
    return " ".join(convert_symbol(s, term) for s in rhs.split())


def render_grammar(grouped, term) -> str:
    lines: list[str] = []
    for nt, (_lineno, rhs_list) in sorted(grouped.items(), key=lambda kv: kv[1][0]):
        alts = [convert_rhs(r, term) for r in rhs_list]
        if not alts:
            continue
        if len(alts) == 1:
            lines.append(f"{nt} ::= {alts[0]}")
        else:
            lines.append(f"{nt} ::=")
            lines.append(f"      {alts[0]}")
            for alt in alts[1:]:
                lines.append(f"    | {alt}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


PAGE_TEMPLATE = """---
sidebar_position: 3
sidebar_label: "Formal Grammar"
slug: /grammar-formal
---

<!-- AUTO-GENERATED by src/smt/gen_grammar_doc.py -- do not edit by hand. -->

# Formal Grammar

This is the **exact** grammar of the TaskNet language, generated directly from
the parser (`src/smt/tasknet_parser.py`). Terminals are shown with their
concrete spelling (e.g. `"{{"`, `";"`, `"tasknet"`); `name`, `number`, and
`string` are lexical tokens; `ε` denotes the empty production.

For a friendlier, example-driven overview, see the [Grammar](grammar.md) page.
For the full language semantics, see the [Manual](manual.md).

```ebnf
{grammar}```
"""


def main() -> None:
    here = Path(__file__).resolve().parent
    repo = here.parents[1]
    parser_src = (here / "tasknet_parser.py").read_text(encoding="utf-8")

    # Keep the raw grammar.txt in sync too.
    extract_grammar.main()

    prods = extract_grammar.extract_productions(parser_src)
    grouped = extract_grammar.collect_grammar_lines(prods)
    term = build_terminal_map(parser_src)
    grammar = render_grammar(grouped, term)

    out = repo / "website" / "docs" / "reference" / "grammar-formal.md"
    out.write_text(PAGE_TEMPLATE.format(grammar=grammar), encoding="utf-8")
    print(f"Wrote {out.relative_to(repo)} ({len(grouped)} non-terminals)")


if __name__ == "__main__":
    main()
